[package]
name = "flux-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"

tracing = "0.1.41"
tracing-subscriber = "0.3.19"

serde = { version = "1.0.217", features = ["derive"] }
