[package]
name = "flux-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"

tracing = "0.1.41"
tracing-subscriber = "0.3.19"

serde = { version = "1.0.218", features = ["derive"] }

tonic = "0.12.3"
